service:
  name: authorization-service

frameworkVersion: "2"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: "webpack.config.js" # Name of webpack configuration file

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  stage: dev
  httpApi:
    cors: true

  environment:
    pryvvid: ${env:pryvvid}

resources:
  Outputs:
    BasicAuthorizerArn:
      Value:
        Fn::GetAtt: [basicAuthorizer, Arn]
      Export:
        Name: "${self:service}:${self:provider.stage}:BasicAuthorizerArn"

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer
