service:
  name: import-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "2"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: "webpack.config.js" # Name of webpack configuration file

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  stage: dev
  httpApi:
    cors: true

  environment:
    SQS_URL:
      Ref: ${cf:product-service.catalogItemsQueue}

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::rs-store-aws"
    - Effect: "Allow"
      Action: "s3:*"
      Resource:
        - "arn:aws:s3:::rs-store-aws/*"
    - Effect: "Allow"
      Action: "sqs:*"
      Resource:
        Fn::GetAtt:
          - ${cf:product-service.catalogItemsQueue}
          - Arn

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - httpApi:
          path: /import
          method: get
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: rs-store-aws
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
